// Package pin offset specifications
// This file was generated by data/specs_tsv_to_js

SC.specsPackage = {
    "TO-1": {
        "x": 58,
        "y": 37
    },
    "TO-5": {
        "x": 58,
        "y": 37
    },
    "TO-92": {
        "x": 37,
        "y": 37
    },
    "TO-126": {
        "x": 37,
        "y": 37
    },
    "TO-220": {
        "x": 37,
        "y": 37
    }
};