// Transistor specifications
// This file was generated by data/specs_tsv_to_js

SC.specsTransistor = {
    "BC547": {
        "kind": "NPN",
        "package": "TO-92",
        "pinout": "CBE"
    },
    "2N3904": {
        "kind": "NPN",
        "package": "TO-92",
        "pinout": "EBC"
    },
    "2N3906": {
        "kind": "PNP",
        "package": "TO-92",
        "pinout": "EBC"
    },
    "2N2222": {
        "kind": "NPN",
        "package": "TO-92",
        "pinout": "EBC"
    },
    "BD139": {
        "kind": "NPN",
        "package": "TO-126",
        "pinout": "ECB"
    },
    "BD241C": {
        "kind": "NPN",
        "package": "TO-220",
        "pinout": "BCE"
    },
    "BC557": {
        "kind": "PNP",
        "package": "TO-92",
        "pinout": "CBE"
    },
    "BC108": {
        "kind": "NPN",
        "package": "TO-1",
        "pinout": "CBE"
    },
    "BC338": {
        "kind": "NPN",
        "package": "TO-92",
        "pinout": "CBE"
    },
    "2N5401": {
        "kind": "PNP",
        "package": "TO-92",
        "pinout": "EBC"
    },
    "2N5551": {
        "kind": "NPN",
        "package": "TO-92",
        "pinout": "EBC"
    },
    "A42": {
        "kind": "NPN",
        "package": "TO-92",
        "pinout": "EBC"
    },
    "A92": {
        "kind": "PNP",
        "package": "TO-92",
        "pinout": "EBC"
    },
    "A733": {
        "kind": "PNP",
        "package": "TO-92",
        "pinout": "ECB"
    },
    "A1015": {
        "kind": "PNP",
        "package": "TO-92",
        "pinout": "ECB"
    },
    "C945": {
        "kind": "NPN",
        "package": "TO-92",
        "pinout": "ECB"
    },
    "C1815": {
        "kind": "NPN",
        "package": "TO-92",
        "pinout": "ECB"
    },
    "S8050": {
        "kind": "NPN",
        "package": "TO-92",
        "pinout": "EBC"
    },
    "S8550": {
        "kind": "PNP",
        "package": "TO-92",
        "pinout": "EBC"
    },
    "S9012": {
        "kind": "PNP",
        "package": "TO-92",
        "pinout": "EBC"
    },
    "S9013": {
        "kind": "NPN",
        "package": "TO-92",
        "pinout": "EBC"
    },
    "S9014": {
        "kind": "NPN",
        "package": "TO-92",
        "pinout": "EBC"
    },
    "S9015": {
        "kind": "PNP",
        "package": "TO-92",
        "pinout": "EBC"
    },
    "S9018": {
        "kind": "NPN",
        "package": "TO-92",
        "pinout": "EBC"
    },
    "MPSA12": {
        "kind": "NPN_DARLINGTON",
        "package": "TO-92",
        "pinout": "EBC"
    },
    "BC546": {
        "kind": "NPN",
        "package": "TO-92",
        "pinout": "CBE"
    },
    "MPSA06": {
        "kind": "NPN",
        "package": "TO-92",
        "pinout": "EBC"
    },
    "2N5088": {
        "kind": "NPN",
        "package": "TO-92",
        "pinout": "EBC"
    },
    "2N5089": {
        "kind": "NPN",
        "package": "TO-92",
        "pinout": "EBC"
    },
    "2N5306": {
        "kind": "NPN_DARLINGTON",
        "package": "TO-92",
        "pinout": "EBC"
    },
    "BC549": {
        "kind": "NPN",
        "package": "TO-92",
        "pinout": "CBE"
    },
    "2N1307": {
        "kind": "PNP",
        "package": "TO-5",
        "pinout": "CBE"
    },
    "2N3391": {
        "kind": "NPN",
        "package": "TO-92",
        "pinout": "ECB"
    },
    "BC184C": {
        "kind": "NPN",
        "package": "TO-92",
        "pinout": "CBE"
    },
    "BC169B": {
        "kind": "NPN",
        "package": "TO-92",
        "pinout": "ECB"
    },
    "BC550": {
        "kind": "NPN",
        "package": "TO-92",
        "pinout": "CBE"
    },
    "BC559": {
        "kind": "PNP",
        "package": "TO-92",
        "pinout": "CBE"
    },
    "BC560": {
        "kind": "PNP",
        "package": "TO-92",
        "pinout": "CBE"
    },
    "BC337": {
        "kind": "NPN",
        "package": "TO-92",
        "pinout": "CBE"
    },
    "BC239": {
        "kind": "NPN",
        "package": "TO-92",
        "pinout": "CBE"
    },
    "BC109": {
        "kind": "NPN",
        "package": "TO-1",
        "pinout": "CBE"
    },
    "TIP120": {
        "kind": "NPN_DARLINGTON",
        "package": "TO-220",
        "pinout": "BCE"
    },
    "2N2925": {
        "kind": "NPN",
        "package": "TO-92",
        "pinout": "EBC"
    },
    "AC176": {
        "kind": "NPN",
        "package": "TO-5",
        "pinout": "CBE"
    },
    "MPS8098": {
        "kind": "NPN",
        "package": "TO-92",
        "pinout": "EBC"
    },
    "BC213L": {
        "kind": "PNP",
        "package": "TO-92",
        "pinout": "EBC"
    },
    "BC183L": {
        "kind": "NPN",
        "package": "TO-92",
        "pinout": "ECB"
    },
    "BD136": {
        "kind": "PNP",
        "package": "TO-126",
        "pinout": "ECB"
    },
    "ZTX705": {
        "kind": "PNP_DARLINGTON",
        "package": "TO-92",
        "pinout": "EBC"
    },
    "IRF540N": {
        "kind": "N_MOSFET",
        "package": "TO-220",
        "pinout": "GDS"
    },
    "IRF5305": {
        "kind": "P_MOSFET",
        "package": "TO-220",
        "pinout": "GDS"
    },
    "IRLZ44N": {
        "kind": "N_MOSFET",
        "package": "TO-220",
        "pinout": "GDS"
    },
    "BS170": {
        "kind": "N_MOSFET",
        "package": "TO-92",
        "pinout": "DGS"
    },
    "MPSA18": {
        "kind": "NPN",
        "package": "TO-92",
        "pinout": "EBC"
    },
    "2N4401": {
        "kind": "NPN",
        "package": "TO-92",
        "pinout": "EBC"
    },
    "2N4403": {
        "kind": "PNP",
        "package": "TO-92",
        "pinout": "EBC"
    },
    "2N4402": {
        "kind": "PNP",
        "package": "TO-92",
        "pinout": "CBE"
    },
    "2N4125": {
        "kind": "PNP",
        "package": "TO-92",
        "pinout": "EBC"
    },
    "2N2907": {
        "kind": "PNP",
        "package": "TO-92",
        "pinout": "CBE"
    },
    "J201": {
        "kind": "N_JFET",
        "package": "TO-92",
        "pinout": "DSG"
    },
    "MPF102": {
        "kind": "N_JFET",
        "package": "TO-92",
        "pinout": "DSG"
    },
    "2N5457": {
        "kind": "N_JFET",
        "package": "TO-92",
        "pinout": "DSG"
    },
    "2N5952": {
        "kind": "N_JFET",
        "package": "TO-92",
        "pinout": "GSD"
    },
    "BF245A": {
        "kind": "N_JFET",
        "package": "TO-92",
        "pinout": "GSD"
    },
    "2SK30A": {
        "kind": "N_JFET",
        "package": "TO-92",
        "pinout": "SGD"
    },
    "2SK246": {
        "kind": "N_JFET",
        "package": "TO-92",
        "pinout": "SGD"
    },
    "2SC536": {
        "kind": "NPN",
        "package": "TO-92",
        "pinout": "ECB"
    },
    "78L33": {
        "kind": "P_REGULATOR",
        "package": "TO-92",
        "pinout": "OGI"
    },
    "78L05": {
        "kind": "P_REGULATOR",
        "package": "TO-92",
        "pinout": "OGI"
    },
    "78L06": {
        "kind": "P_REGULATOR",
        "package": "TO-92",
        "pinout": "OGI"
    },
    "78L08": {
        "kind": "P_REGULATOR",
        "package": "TO-92",
        "pinout": "OGI"
    },
    "78L09": {
        "kind": "P_REGULATOR",
        "package": "TO-92",
        "pinout": "OGI"
    },
    "78L12": {
        "kind": "P_REGULATOR",
        "package": "TO-92",
        "pinout": "OGI"
    },
    "78L15": {
        "kind": "P_REGULATOR",
        "package": "TO-92",
        "pinout": "OGI"
    },
    "79L05": {
        "kind": "N_REGULATOR",
        "package": "TO-92",
        "pinout": "GIO"
    },
    "79L06": {
        "kind": "N_REGULATOR",
        "package": "TO-92",
        "pinout": "GIO"
    },
    "79L08": {
        "kind": "N_REGULATOR",
        "package": "TO-92",
        "pinout": "GIO"
    },
    "79L09": {
        "kind": "N_REGULATOR",
        "package": "TO-92",
        "pinout": "GIO"
    },
    "79L12": {
        "kind": "N_REGULATOR",
        "package": "TO-92",
        "pinout": "GIO"
    },
    "79L15": {
        "kind": "N_REGULATOR",
        "package": "TO-92",
        "pinout": "GIO"
    },
    "L7805": {
        "kind": "P_REGULATOR",
        "package": "TO-220",
        "pinout": "IGO"
    },
    "L7806": {
        "kind": "P_REGULATOR",
        "package": "TO-220",
        "pinout": "IGO"
    },
    "L7808": {
        "kind": "P_REGULATOR",
        "package": "TO-220",
        "pinout": "IGO"
    },
    "L7809": {
        "kind": "P_REGULATOR",
        "package": "TO-220",
        "pinout": "IGO"
    },
    "L7812": {
        "kind": "P_REGULATOR",
        "package": "TO-220",
        "pinout": "IGO"
    },
    "L7815": {
        "kind": "P_REGULATOR",
        "package": "TO-220",
        "pinout": "IGO"
    },
    "L7905": {
        "kind": "N_REGULATOR",
        "package": "TO-220",
        "pinout": "GIO"
    },
    "L7906": {
        "kind": "N_REGULATOR",
        "package": "TO-220",
        "pinout": "GIO"
    },
    "L7908": {
        "kind": "N_REGULATOR",
        "package": "TO-220",
        "pinout": "GIO"
    },
    "L7909": {
        "kind": "N_REGULATOR",
        "package": "TO-220",
        "pinout": "GIO"
    },
    "L7912": {
        "kind": "N_REGULATOR",
        "package": "TO-220",
        "pinout": "GIO"
    },
    "L7915": {
        "kind": "N_REGULATOR",
        "package": "TO-220",
        "pinout": "GIO"
    },
    "LM317": {
        "kind": "P_REGULATOR",
        "package": "TO-220",
        "pinout": "GOI"
    },
    "NKT213": {
        "kind": "PNP",
        "package": "TO-1",
        "pinout": "EBC"
    },
    "NKT275": {
        "kind": "PNP",
        "package": "TO-1",
        "pinout": "CBE"
    }
};