// Component pins specification
// This file was generated by data/specs_tsv_to_js

SC.specsPin = {
    "resistor": [
        {
            "x": 20,
            "y": 0,
            "name": "A"
        },
        {
            "x": 20,
            "y": 60,
            "name": "B"
        }
    ],
    "sinewave": [
        {
            "x": 20,
            "y": 0,
            "name": "A"
        },
        {
            "x": 20,
            "y": 60,
            "name": "B"
        }
    ],
    "ldr": [
        {
            "x": 20,
            "y": 0,
            "name": "A"
        },
        {
            "x": 20,
            "y": 60,
            "name": "B"
        }
    ],
    "potentiometer": [
        {
            "x": 20,
            "y": 60,
            "name": "Start"
        },
        {
            "x": 0,
            "y": 40,
            "name": "Wiper"
        },
        {
            "x": 20,
            "y": 0,
            "name": "End"
        }
    ],
    "spst": [
        {
            "x": 20,
            "y": 0,
            "name": "1"
        },
        {
            "x": 20,
            "y": 60,
            "name": "2"
        }
    ],
    "spdt": [
        {
            "x": 20,
            "y": 0,
            "name": "1"
        },
        {
            "x": 20,
            "y": 60,
            "name": "2"
        },
        {
            "x": 40,
            "y": 60,
            "name": "3"
        }
    ],
    "dpdt1": [
        {
            "x": 0,
            "y": 20,
            "name": "1"
        },
        {
            "x": 0,
            "y": 40,
            "name": "2"
        },
        {
            "x": 0,
            "y": 60,
            "name": "3"
        },
        {
            "x": 60,
            "y": 60,
            "name": "4"
        },
        {
            "x": 60,
            "y": 40,
            "name": "5"
        },
        {
            "x": 60,
            "y": 20,
            "name": "6"
        }
    ],
    "dpdt2": [
        {
            "x": 60,
            "y": 20,
            "name": "1"
        },
        {
            "x": 0,
            "y": 40,
            "name": "2"
        },
        {
            "x": 60,
            "y": 40,
            "name": "3"
        },
        {
            "x": 60,
            "y": 80,
            "name": "4"
        },
        {
            "x": 0,
            "y": 80,
            "name": "5"
        },
        {
            "x": 60,
            "y": 60,
            "name": "6"
        }
    ],
    "capacitor": [
        {
            "x": 20,
            "y": 0,
            "name": "A"
        },
        {
            "x": 20,
            "y": 60,
            "name": "B"
        }
    ],
    "capacitor_pol": [
        {
            "x": 20,
            "y": 0,
            "name": "A"
        },
        {
            "x": 20,
            "y": 60,
            "name": "B"
        }
    ],
    "diode": [
        {
            "x": 20,
            "y": 0,
            "name": "A"
        },
        {
            "x": 20,
            "y": 60,
            "name": "B"
        }
    ],
    "led": [
        {
            "x": 20,
            "y": 0,
            "name": "A"
        },
        {
            "x": 20,
            "y": 60,
            "name": "B"
        }
    ],
    "connector": [
        {
            "x": 0,
            "y": 20,
            "name": "A"
        }
    ],
    "ground": [
        {
            "x": 20,
            "y": 0,
            "name": "GND"
        }
    ],
    "dc_voltage_supply": [
        {
            "x": 20,
            "y": 0,
            "name": "P"
        },
        {
            "x": 20,
            "y": 60,
            "name": "N"
        }
    ],
    "battery": [
        {
            "x": 20,
            "y": 0,
            "name": "P"
        },
        {
            "x": 20,
            "y": 60,
            "name": "N"
        }
    ],
    "transistor_n_jfet": [
        {
            "x": 40,
            "y": 0,
            "name": "D"
        },
        {
            "x": 0,
            "y": 20,
            "name": "G"
        },
        {
            "x": 40,
            "y": 40,
            "name": "S"
        }
    ],
    "transistor_n_mosfet": [
        {
            "x": 40,
            "y": 0,
            "name": "D"
        },
        {
            "x": 0,
            "y": 20,
            "name": "G"
        },
        {
            "x": 40,
            "y": 40,
            "name": "S"
        }
    ],
    "transistor_p_mosfet": [
        {
            "x": 40,
            "y": 0,
            "name": "D"
        },
        {
            "x": 0,
            "y": 20,
            "name": "G"
        },
        {
            "x": 40,
            "y": 40,
            "name": "S"
        }
    ],
    "transistor_p_jfet": [
        {
            "x": 40,
            "y": 0,
            "name": "D"
        },
        {
            "x": 0,
            "y": 20,
            "name": "G"
        },
        {
            "x": 40,
            "y": 40,
            "name": "S"
        }
    ],
    "transistor_npn": [
        {
            "x": 40,
            "y": 0,
            "name": "C"
        },
        {
            "x": 0,
            "y": 20,
            "name": "B"
        },
        {
            "x": 40,
            "y": 40,
            "name": "E"
        }
    ],
    "transistor_npn_darlington": [
        {
            "x": 60,
            "y": 0,
            "name": "C"
        },
        {
            "x": 0,
            "y": 20,
            "name": "B"
        },
        {
            "x": 60,
            "y": 60,
            "name": "E"
        }
    ],
    "transistor_pnp": [
        {
            "x": 40,
            "y": 0,
            "name": "C"
        },
        {
            "x": 0,
            "y": 20,
            "name": "B"
        },
        {
            "x": 40,
            "y": 40,
            "name": "E"
        }
    ],
    "transistor_pnp_darlington": [
        {
            "x": 60,
            "y": 60,
            "name": "C"
        },
        {
            "x": 0,
            "y": 40,
            "name": "B"
        },
        {
            "x": 60,
            "y": 0,
            "name": "E"
        }
    ],
    "dip8": [
        {
            "x": 0,
            "y": 20,
            "name": "P1"
        },
        {
            "x": 0,
            "y": 40,
            "name": "P2"
        },
        {
            "x": 0,
            "y": 60,
            "name": "P3"
        },
        {
            "x": 0,
            "y": 80,
            "name": "P4"
        },
        {
            "x": 60,
            "y": 80,
            "name": "P5"
        },
        {
            "x": 60,
            "y": 60,
            "name": "P6"
        },
        {
            "x": 60,
            "y": 40,
            "name": "P7"
        },
        {
            "x": 60,
            "y": 20,
            "name": "P8"
        }
    ],
    "dip8_opamp_single": [
        {
            "x": 0,
            "y": 20,
            "name": "OFS1"
        },
        {
            "x": 0,
            "y": 40,
            "name": "IN-"
        },
        {
            "x": 0,
            "y": 60,
            "name": "IN+"
        },
        {
            "x": 0,
            "y": 80,
            "name": "V-"
        },
        {
            "x": 60,
            "y": 80,
            "name": "OFS2"
        },
        {
            "x": 60,
            "y": 60,
            "name": "OUT"
        },
        {
            "x": 60,
            "y": 40,
            "name": "V+"
        },
        {
            "x": 60,
            "y": 20,
            "name": "NC1"
        }
    ],
    "dip8_opamp_dual": [
        {
            "x": 0,
            "y": 20,
            "name": "P1"
        },
        {
            "x": 0,
            "y": 40,
            "name": "P2"
        },
        {
            "x": 0,
            "y": 60,
            "name": "P3"
        },
        {
            "x": 0,
            "y": 80,
            "name": "P4"
        },
        {
            "x": 60,
            "y": 80,
            "name": "P5"
        },
        {
            "x": 60,
            "y": 60,
            "name": "P6"
        },
        {
            "x": 60,
            "y": 40,
            "name": "P7"
        },
        {
            "x": 60,
            "y": 20,
            "name": "P8"
        }
    ],
    "opamp_triangle_3pin": [
        {
            "x": 0,
            "y": 20,
            "name": "IN+"
        },
        {
            "x": 0,
            "y": 60,
            "name": "IN-"
        },
        {
            "x": 80,
            "y": 40,
            "name": "OUT"
        }
    ],
    "transistor_p_regulator": [
        {
            "x": 0,
            "y": 20,
            "name": "I"
        },
        {
            "x": 20,
            "y": 40,
            "name": "G"
        },
        {
            "x": 40,
            "y": 20,
            "name": "O"
        }
    ],
    "transistor_n_regulator": [
        {
            "x": 0,
            "y": 20,
            "name": "I"
        },
        {
            "x": 20,
            "y": 40,
            "name": "G"
        },
        {
            "x": 40,
            "y": 20,
            "name": "O"
        }
    ],
    "inductor": [
        {
            "x": 20,
            "y": 0,
            "name": "A"
        },
        {
            "x": 20,
            "y": 60,
            "name": "B"
        }
    ],
    "dip4": [
        {
            "x": 0,
            "y": 20,
            "name": "P1"
        },
        {
            "x": 0,
            "y": 40,
            "name": "P2"
        },
        {
            "x": 60,
            "y": 40,
            "name": "P3"
        },
        {
            "x": 60,
            "y": 20,
            "name": "P4"
        }
    ],
    "dip6": [
        {
            "x": 0,
            "y": 20,
            "name": "P1"
        },
        {
            "x": 0,
            "y": 40,
            "name": "P2"
        },
        {
            "x": 0,
            "y": 60,
            "name": "P3"
        },
        {
            "x": 60,
            "y": 60,
            "name": "P4"
        },
        {
            "x": 60,
            "y": 40,
            "name": "P5"
        },
        {
            "x": 60,
            "y": 20,
            "name": "P6"
        }
    ],
    "dip10": [
        {
            "x": 0,
            "y": 20,
            "name": "P1"
        },
        {
            "x": 0,
            "y": 40,
            "name": "P2"
        },
        {
            "x": 0,
            "y": 60,
            "name": "P3"
        },
        {
            "x": 0,
            "y": 80,
            "name": "P4"
        },
        {
            "x": 0,
            "y": 100,
            "name": "P5"
        },
        {
            "x": 60,
            "y": 100,
            "name": "P6"
        },
        {
            "x": 60,
            "y": 80,
            "name": "P7"
        },
        {
            "x": 60,
            "y": 60,
            "name": "P8"
        },
        {
            "x": 60,
            "y": 40,
            "name": "P9"
        },
        {
            "x": 60,
            "y": 20,
            "name": "P10"
        }
    ],
    "dip12": [
        {
            "x": 0,
            "y": 20,
            "name": "P1"
        },
        {
            "x": 0,
            "y": 40,
            "name": "P2"
        },
        {
            "x": 0,
            "y": 60,
            "name": "P3"
        },
        {
            "x": 0,
            "y": 80,
            "name": "P4"
        },
        {
            "x": 0,
            "y": 100,
            "name": "P5"
        },
        {
            "x": 0,
            "y": 120,
            "name": "P6"
        },
        {
            "x": 60,
            "y": 120,
            "name": "P7"
        },
        {
            "x": 60,
            "y": 100,
            "name": "P8"
        },
        {
            "x": 60,
            "y": 80,
            "name": "P9"
        },
        {
            "x": 60,
            "y": 60,
            "name": "P10"
        },
        {
            "x": 60,
            "y": 40,
            "name": "P11"
        },
        {
            "x": 60,
            "y": 20,
            "name": "P12"
        }
    ],
    "dip14": [
        {
            "x": 0,
            "y": 20,
            "name": "P1"
        },
        {
            "x": 0,
            "y": 40,
            "name": "P2"
        },
        {
            "x": 0,
            "y": 60,
            "name": "P3"
        },
        {
            "x": 0,
            "y": 80,
            "name": "P4"
        },
        {
            "x": 0,
            "y": 100,
            "name": "P5"
        },
        {
            "x": 0,
            "y": 120,
            "name": "P6"
        },
        {
            "x": 0,
            "y": 140,
            "name": "P7"
        },
        {
            "x": 60,
            "y": 140,
            "name": "P8"
        },
        {
            "x": 60,
            "y": 120,
            "name": "P9"
        },
        {
            "x": 60,
            "y": 100,
            "name": "P10"
        },
        {
            "x": 60,
            "y": 80,
            "name": "P11"
        },
        {
            "x": 60,
            "y": 60,
            "name": "P12"
        },
        {
            "x": 60,
            "y": 40,
            "name": "P13"
        },
        {
            "x": 60,
            "y": 20,
            "name": "P14"
        }
    ],
    "dip16": [
        {
            "x": 0,
            "y": 20,
            "name": "P1"
        },
        {
            "x": 0,
            "y": 40,
            "name": "P2"
        },
        {
            "x": 0,
            "y": 60,
            "name": "P3"
        },
        {
            "x": 0,
            "y": 80,
            "name": "P4"
        },
        {
            "x": 0,
            "y": 100,
            "name": "P5"
        },
        {
            "x": 0,
            "y": 120,
            "name": "P6"
        },
        {
            "x": 0,
            "y": 140,
            "name": "P7"
        },
        {
            "x": 0,
            "y": 160,
            "name": "P8"
        },
        {
            "x": 60,
            "y": 160,
            "name": "P9"
        },
        {
            "x": 60,
            "y": 140,
            "name": "P10"
        },
        {
            "x": 60,
            "y": 120,
            "name": "P11"
        },
        {
            "x": 60,
            "y": 100,
            "name": "P12"
        },
        {
            "x": 60,
            "y": 80,
            "name": "P13"
        },
        {
            "x": 60,
            "y": 60,
            "name": "P14"
        },
        {
            "x": 60,
            "y": 40,
            "name": "P15"
        },
        {
            "x": 60,
            "y": 20,
            "name": "P16"
        }
    ],
    "ammeter": [
        {
            "x": 20,
            "y": 0,
            "name": "P"
        },
        {
            "x": 20,
            "y": 60,
            "name": "N"
        }
    ],
    "ota_triangle_5pin": [
        {
            "x": 0,
            "y": 20,
            "name": "IN+"
        },
        {
            "x": 0,
            "y": 40,
            "name": "DB"
        },
        {
            "x": 0,
            "y": 60,
            "name": "IN-"
        },
        {
            "x": 80,
            "y": 40,
            "name": "OUT"
        },
        {
            "x": 60,
            "y": 80,
            "name": "IB"
        }
    ],
    "ota_buffer": [
        {
            "x": 0,
            "y": 20,
            "name": "BI"
        },
        {
            "x": 60,
            "y": 20,
            "name": "BO"
        }
    ],
    "inductor_coupling": [
        {
            "x": 20,
            "y": 0,
            "name": "NC"
        }
    ]
};